# 使用 Ctrl f 作为 prefix
set -g prefix 'C-f'


# 真彩色支持
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -as terminal-overrides ",*:RGB"
set -sg escape-time 10
# 让 window 的编号和 pane 的编号从 2 开始
set -g base-index 2
setw -g pane-base-index 2

set-option -g set-titles on

# 使用 Alt + num 来选择不同的 window
bind-key -n M-0 select-window -t 1
bind-key -n M-1 select-window -t 2
bind-key -n M-2 select-window -t 3
bind-key -n M-3 select-window -t 4
bind-key -n M-4 select-window -t 5
bind-key -n M-5 select-window -t 6
bind-key -n M-6 select-window -t 7
bind-key -n M-7 select-window -t 8
bind-key -n M-8 select-window -t 9

# 使用 Ctrl + hljk 来在不同的 pane 中移动
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# 调整 pane 大小
bind -r H resize-pane -L 3  # 更精细的调整
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 3

# 增加状态栏的对比度
setw -g window-status-current-style fg=black,bg=yellow
# 将默认在底部的状态栏移动到上面去
set-option -g status-position top

# 可以用鼠标直接调整 pane 的大小
set -g mouse on

# 让 window 的各种操作使用 vim 模式
set-window-option -g mode-keys vi

# 给当前窗口添加 emoji 表情
set-option -g window-status-current-format  '🧀 #{window_index}:#{b:pane_current_path}'

# 创建新的 window
bind c new-window -c "#{pane_current_path}"
# 水平创建新的 pane
bind '\' split-window -c "#{pane_current_path}"
# 垂直创建新的 pane
bind '|' split-window -h -c "#{pane_current_path}"

# 将 window 的名称自动修改为路径名称，便于区分
set-option -g status-interval 4
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# prefix v 进入到 copy mode
bind-key -T prefix v copy-mode

# https://superuser.com/questions/395162/tmux-copy-mode-select-text-block
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
# bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.

# https://superuser.com/questions/343576/how-do-i-reorder-tmux-windows
# 使用 「Ctrl Shift 方向键」调整 window 的位置
bind-key -n C-S-Left swap-window -t 3\; select-window -t -1
bind-key -n C-S-Right swap-window -t +5\; select-window -t +1

# 使用 prefix f 直接进入到搜索
# https://stackoverflow.com/questions/66430864/on-tmux-2-4-how-to-enter-copy-mode-and-start-a-search-all-in-one-go
bind f copy-mode \; command-prompt -p "(search up)" "send -X search-forward \"%%%\""
bind -T copy-mode-vi f copy-mode \; command-prompt -p "(search up)" "send -X search-forward \"%%%\""

# Alt + h / l 来切换 session
# bind-key -n M-h switch-client -n
# bind-key -n M-l switch-client -p

# 切换到上一个窗口
bind-key -n M-k previous-window
# 切换到下一个窗口
bind-key -n M-j next-window


# bind j switch-client -n
# bind k switch-client -p

# 使用 prefix+q 关闭当前 pane
bind q kill-pane

# 拷贝之后不要默认自动进入到 normal mode
set -g @yank_action 'copy-pipe'

# WSL 下使用 win32yank 处理剪贴板，避免中文乱码
set -g @override_copy_command '/mnt/c/tools/neovim/nvim-win64/bin/win32yank.exe -i --crlf'
set -g @override_paste_command '/mnt/c/tools/neovim/nvim-win64/bin/win32yank.exe -o --lf'

# 加载插件
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # 默认配置
set -g @plugin 'tmux-plugins/tmux-resurrect' # 关机保存 session
set -g @plugin 'tmux-plugins/tmux-continuum' # 自动保存和恢复
set -g @plugin 'tmux-plugins/tmux-yank' # 方便的拷贝到系统剪切板

# tmux-resurrect 配置
set -g @resurrect-capture-pane-contents 'on' # 保存 pane 内容
set -g @resurrect-strategy-vim 'session' # 恢复 vim session
set -g @resurrect-strategy-nvim 'session' # 恢复 nvim session

# tmux-continuum 配置
set -g @continuum-restore 'on' # 启动 tmux 时自动恢复
set -g @continuum-save-interval '15' # 每 15 分钟自动保存

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
