allinstall:
	make selflearninginstall
	make picinstall
	make personalconfiginstall
personalconfiginstall:
	bash ./personal-config-install.sh
selflearninginstall:
	bash ./self-learning-install.sh
picinstall:
	bash ./picture-sync.sh
