onboarding = false

[theme]
name = "nord"

[keys]
prefix = "ctrl+f"
detach = "prefix+d"
reload_config = "prefix+alt+r"
open_notification_target = "prefix+shift+o"
new_workspace = "prefix+n"
rename_workspace = "prefix+shift+r"
previous_workspace = "alt+h"
next_workspace = "alt+l"
new_tab = "prefix+c"
rename_tab = "prefix+r"
previous_tab = "alt+j"
next_tab = "alt+k"
close_tab = "prefix+ampersand"
edit_scrollback = "prefix+v"
focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"
cycle_pane_next = "prefix+o"
split_vertical = "prefix+|"
split_horizontal = "prefix+\\"
close_pane = "prefix+q"
zoom = "prefix+z"
resize_mode = "prefix+shift+z"

[keys.indexed]
tabs = "alt"

[ui.toast]
delivery = "herdr"

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_scope = "current"

[experimental]
switch_ascii_input_source_in_prefix = false
pane_history = false

[ui.sound]
enabled = false
